version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  pg4:
    image: dpage/pgadmin4
    container_name: pg4
    restart: always
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=syspass